theme = "deepwhite"

[editor]
mouse = false
scrolloff = 999
idle-timeout = 150

shell = ["nu", "--stdin", "-c"]
line-number = "relative"
bufferline = "multiple"

cursorline = true
true-color = true
color-modes = true

default-line-ending = "lf"
end-of-line-diagnostics = "hint"

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name"]
right = [
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "read-only-indicator",
  "file-type",
]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.smart-tab]
enable = true
supersede-menu = false

[editor.inline-diagnostics]
cursor-line = "warning"

[keys.normal]
y = "move_char_left"
n = "move_visual_line_down"
i = "move_visual_line_up"
o = "move_char_right"
d = "move_next_word_end"
D = "move_next_long_word_end"
k = "find_till_char"
t = "find_next_char"
K = "till_prev_char"
T = "find_prev_char"
f = "replace"
F = "replace_with_yanked"
r = "insert_mode"
R = "insert_at_line_start"
l = "open_below"
L = "open_above"
j = "yank"
h = "collapse_selection"
H = "command_mode"
e = "delete_selection"
N = "join_selections"
I = "keep_selections"
p = "search_next"
P = "search_prev"
c = "change_selection_noyank"
"0" = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_last_line"

";" = "paste_after"
":" = "paste_before"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"

"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]
"^" = [":pipe into string | split row \"\\n\" | sort | uniq | str join \"\\n\""]

[keys.normal.z]
n = "scroll_down"
i = "scroll_up"

[keys.normal.g]
c = "toggle_comments"

[keys.normal.m]
i = "no_op"
d = "no_op"
r = "select_textobject_inner"
e = "surround_delete"
c = "surround_replace"

[keys.normal."space"]
m = ":fmt"
F = "file_picker_in_current_buffer_directory"
";" = "paste_clipboard_after"
":" = "paste_clipboard_before"

[keys.normal."space".q]
q = ":buffer-close!"
w = ":write-buffer-close"
a = ":write-quit-all"

[keys.normal."space".w]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
H = "no_op"
J = "no_op"
K = "no_op"
L = "no_op"
"C-h" = "no_op"
"C-j" = "no_op"
"C-k" = "no_op"
"C-l" = "no_op"
c = "wonly"
y = "jump_view_left"
n = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"
Y = "swap_view_left"
N = "swap_view_down"
I = "swap_view_up"
O = "swap_view_right"

[keys.insert]
"C-n" = "goto_next_tabstop"
"C-i" = "goto_prev_tabstop"

[keys.select]
y = "extend_char_left"
o = "extend_char_right"
n = "extend_visual_line_down"
i = "extend_visual_line_up"
d = "extend_next_word_end"
D = "extend_next_long_word_end"
k = "find_till_char"
t = "find_next_char"
K = "till_prev_char"
T = "find_prev_char"
f = "replace"
F = "replace_with_yanked"
r = "insert_mode"
R = "insert_at_line_start"
l = "open_below"
L = "open_above"
j = "yank"
h = "collapse_selection"
H = "command_mode"
e = "delete_selection"
N = "join_selections"
I = "keep_selections"
p = "search_next"
P = "search_prev"
";" = "paste_after"
":" = "paste_before"
"0" = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_last_line"
"A-h" = "flip_selections"
"A-H" = "ensure_selections_forward"

"^" = [":pipe into string | split row \"\\n\" | sort | uniq | str join \"\\n\""]

[keys.select."space"]
m = ":fmt"
y = "no_op"
Y = "no_op"
j = "yank_to_clipboard"
J = "yank_main_selection_to_clipboard"
p = "no_op"
P = "no_op"
";" = "paste_clipboard_after"
":" = "paste_clipboard_before"
