theme = "deepwhite"

[editor]
mouse = false
scrolloff = 999
idle-timeout = 200

line-number = "relative"
bufferline = "multiple"
cursorline = true
true-color = true
color-modes = true

auto-format = false
auto-save = true

default-line-ending = "lf"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.statusline]
left = ["mode", "spinner","diagnostics"]
center = ["file-name"]
right = ["selections", "position", "file-encoding", "file-line-ending", "read-only-indicator", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[editor.smart-tab]
enable = false
supersede-menu = true

[keys.normal]
y = "move_char_left"
n = "move_visual_line_down"
i = "move_visual_line_up"
o = "move_char_right"
d = "move_next_word_end"
D = "move_next_long_word_end"
k = "find_till_char"
t = "find_next_char"
K = "till_prev_char"
T = "find_prev_char"
f = "replace"
F = "replace_with_yanked"
r = "insert_mode"
R = "insert_at_line_start"
l = "open_below"
L = "open_above"
j = "yank"
h = "collapse_selection"
H = "command_mode"
e = "delete_selection"
N = "join_selections"
I = "keep_selections"
p = "search_next"
P = "search_prev"
"0" = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_last_line"

";" = "paste_after"
":" = "paste_before"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"

[keys.normal.z]
n = "scroll_down"
i = "scroll_up"

[keys.normal.m]
r = "select_textobject_inner"

[keys.normal."space"]
m = ":fmt"

[keys.normal."space".q]
q = ":buffer-close!"
w = ":write-buffer-close"
a = ":write-quit-all"

[keys.normal."space".w]
h = "no_op"
j = "no_op"
k = "no_op"
l = "no_op"
"C-h" = "no_op"
"C-j" = "no_op"
"C-k" = "no_op"
"C-l" = "no_op"
y = "jump_view_left"
n = "jump_view_down"
i = "jump_view_up"
o = "jump_view_right"
c = "wonly"

[keys.select]
y = "extend_char_left"
o = "extend_char_right"
n = "extend_visual_line_down"
i = "extend_visual_line_up"
d = "extend_next_word_end"
D = "extend_next_long_word_end"
k = "find_till_char"
t = "find_next_char"
K = "till_prev_char"
T = "find_prev_char"
f = "replace"
F = "replace_with_yanked"
r = "insert_mode"
R = "insert_at_line_start"
l = "open_below"
L = "open_above"
j = "yank"
h = "collapse_selection"
H = "command_mode"
e = "delete_selection"
N = "join_selections"
I = "keep_selections"
p = "search_next"
P = "search_prev"
";" = "paste_after"
":" = "paste_before"
"0" = "goto_line_start"
"$" = "goto_line_end"
"G" = "goto_last_line"
