[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true

[language-server.ruff]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = ["--preview", "--quiet", "-"]
