[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
useLibraryCodeForTypes = false
autoImportCompletions = true

[language-server.ruff]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = ["--preview", "--quiet", "-"]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }

[[language]]
name = "vue"
formatter = { command = 'prettier', args = ["--parser", "vue"] }
