[language-server.ty]
command = "ty"
args = ["server"]
config = { experimental = { rename = true } }

[[language]]
name = "python"
auto-format = true
language-servers = ["ty", "ruff"]

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[[language]]
name = "vue"
formatter = { command = 'prettier', args = ["--parser", "vue"] }
roots = ["package.json", "vue.config.js"]
